(() => {
'use strict';
const D=window.DSData,$=s=>document.querySelector(s),modal=$('#asset-dialog'),body=$('#modal-body');
const localService=['127.0.0.1','localhost','[::1]'].includes(location.hostname)&&location.protocol==='http:';
let folderRecords=[],currentFolder=null;
let records=[],documents=[],selected=new Set(),tab=new URLSearchParams(location.search).get('tab')||'group',urls=[],generation=0,busy=false;
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
const button=(text,fn,cls)=>{const b=el('button',text,cls);b.onclick=()=>Promise.resolve(fn()).catch(fail);return b};
function notify(text){$('#message').textContent=text;$('#message').classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#message').classList.remove('show'),5000)}
function fail(error){busy=false;notify(error.message||'操作失败，请重试');const n=el('p',error.message||'操作失败，请重试','notes');n.setAttribute('role','alert');if(modal.open)body.append(n)}
function open(title){generation++;busy=false;$('#modal-title').textContent=title;body.replaceChildren();if(!modal.open)modal.showModal();return generation}
function close(){if(busy)return;generation++;modal.close()}
$('#close-modal').onclick=close;modal.addEventListener('cancel',e=>{if(busy)e.preventDefault();else generation++});
function openDS(id){window.top.location.href='ds-studio.html?ds='+encodeURIComponent(id)}
async function refresh(){records=await D.files();folderRecords=await D.folders();documents=(await D.getLibrary())?.documents.filter(d=>d.kind!=='material')||[];selected=new Set([...selected].filter(id=>[...records,...folderRecords,...documents].some(r=>r.id===id)));render()}
function toggleSelected(id){selected.has(id)?selected.delete(id):selected.add(id);render()}
function chosenFiles(){return records.filter(r=>selected.has(r.id)||selected.has(r.folderId))}
function selectionCheck(record){const label=el('label',undefined,'asset-check'),input=el('input');input.type='checkbox';input.checked=selected.has(record.id);input.setAttribute('aria-label','选择 '+record.name);input.onchange=()=>toggleSelected(record.id);label.append(input);return label}
function swatches(colors){const row=el('div',undefined,'swatches');colors.forEach(c=>{const i=el('i');i.style.background=c;row.append(i)});return row}
function render(){urls.forEach(URL.revokeObjectURL);urls=[];renderFolders();const query=$('#search').value.trim().toLowerCase();$('#file-count').textContent=records.length;$('#ds-count').textContent=documents.length;$('#group-view').hidden=tab!=='group';$('#ds-view').hidden=tab!=='ds';document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const filesOnly=tab==='group'&&selected.size>0&&[...selected].every(id=>records.some(r=>r.id===id));$('#start').disabled=!filesOnly;$('#selection-actions').hidden=!selected.size;$('#selected-count').textContent='已选择 '+selected.size+' 项';$('#rename').disabled=selected.size!==1;for(const id of ['analyze-selected','download'])$('#'+id).hidden=!filesOnly;$('#move').hidden=tab!=='group';$('#move').disabled=!filesOnly;$('#move').title=filesOnly?'移动到文件夹':'仅素材文件可移动，文件夹保持单层';document.body.classList.toggle('has-selection',!!selected.size);
  const grid=$('#file-grid');grid.replaceChildren();const visible=records.filter(r=>(r.folderId||null)===currentFolder&&r.name.toLowerCase().includes(query));$('#empty').hidden=!!visible.length||(!currentFolder&&folderRecords.some(f=>f.name.toLowerCase().includes(query)));$('#empty h2').textContent=query?'没有匹配的素材':'你的素材，从这里开始';
  for(const r of visible){const wrapper=el('article',undefined,'asset-card group-card'+(selected.has(r.id)?' selected':'')),card=button('',()=>toggleSelected(r.id),'group-open');card.setAttribute('aria-label',r.name);card.setAttribute('aria-pressed',selected.has(r.id));const art=el('div',undefined,'asset-art');if(r.preview){const img=new Image();img.src=r.preview;img.alt=r.name;art.append(img)}else if(r.blob.type.startsWith('image/')&&!/svg/.test(r.blob.type)){const img=new Image(),url=URL.createObjectURL(r.blob);urls.push(url);img.src=url;img.alt=r.name;art.append(img)}else art.append(el('span',r.name.split('.').pop().toUpperCase().slice(0,8),'file-type'));card.append(art,groupMeta(r.name,size(r.blob.size)+' · '+new Date(r.created).toLocaleDateString()));wrapper.append(card,selectionCheck(r));grid.append(wrapper)}
  const dsGrid=$('#ds-grid');dsGrid.replaceChildren();const add=button('',async()=>{const d=D.make('未命名 DS',['#25262a','#ec593e','#ececef']);await D.upsert(d);openDS(d.id)},'asset-card ds-new');add.append(el('div','＋','asset-art'),el('strong','新建 Design System'),el('p','从空白风格开始'));dsGrid.append(add);
  for(const d of documents.filter(d=>d.name.toLowerCase().includes(query))){const wrapper=el('article',undefined,'asset-card ds-card'+(selected.has(d.id)?' selected':'')),card=button('',()=>selected.size?toggleSelected(d.id):openDS(d.id),'ds-open'),art=el('div',undefined,'asset-art');const image=Object.values(d.assets)[0];if(image){const img=new Image();img.src=image.data;img.alt=d.name;art.append(img)}else{art.style.background=d.tokens.background;const type=el('span','Aa','file-type');type.style.color=d.tokens.primary;type.style.fontFamily=d.tokens.heading;type.style.fontSize='56px';art.append(type)}card.append(art,el('strong',d.name),el('p',d.source?.type==='curated-vi'?'完整 VI · '+d.boards.length+' 个画板':d.source?.type==='website'?'网站视觉 · 可编辑':d.source?'素材解析 · 可编辑':'我的设计系统'),swatches([d.tokens.primary,d.tokens.secondary,d.tokens.background]));const rename=button('重命名',()=>renameDS(d),'ds-rename');rename.setAttribute('aria-label','重命名 '+d.name);wrapper.append(card,selectionCheck(d),rename);dsGrid.append(wrapper)}
  $('#start').disabled=tab!=='group'||!chosenFiles().length;
  [...grid.children].forEach((card,index)=>{const r=visible[index];const preview=button('查看',()=>previewFile(r),'ds-rename');preview.setAttribute('aria-label','查看 '+r.name);card.append(preview)});
  window.lucide?.createIcons();
}
async function previewFile(record){const token=open(record.name),blob=record.blob;const details=el('p',size(blob?.size||0)+' · '+(record.relativePath||record.name),'notes');body.append(details);if(blob?.type.startsWith('image/')&&!blob.type.includes('svg')){const image=new Image();const url=URL.createObjectURL(blob);image.src=url;image.alt=record.name;image.style.cssText='display:block;max-width:100%;max-height:60dvh;object-fit:contain;margin:auto';body.append(image);modal.addEventListener('close',()=>URL.revokeObjectURL(url),{once:true})}else if(blob&&(blob.type.startsWith('text/')||/\.(txt|md|csv|json)$/i.test(record.name))){const text=await blob.slice(0,100000).text();if(token!==generation)return;const pre=el('pre',text);pre.style.cssText='white-space:pre-wrap;overflow-wrap:anywhere;max-height:55dvh;overflow:auto';body.append(pre);if(blob.size>100000)body.append(el('small','预览显示前 100 KB，完整内容请下载原文件'))}else body.append(el('p','该格式暂无内嵌预览，原文件已完整保留。','notes'));if(blob)body.append(button('下载原文件',()=>{const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=record.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}))}
function renderFolders(){
  $('#new-folder').hidden=tab!=='group'||!!currentFolder;const crumb=$('#folder-breadcrumb');crumb.replaceChildren();if(currentFolder){crumb.append(button('Group',()=>{currentFolder=null;selected.clear();render()}),el('span',' / '+(folderRecords.find(f=>f.id===currentFolder)?.name||'')))}
  const grid=$('#folder-grid');grid.replaceChildren();if(currentFolder)return;const query=$('#search').value.trim().toLowerCase();for(const folder of folderRecords.filter(f=>f.name.toLowerCase().includes(query))){const members=records.filter(r=>r.folderId===folder.id),wrapper=el('article',undefined,'asset-card group-card group-folder'+(selected.has(folder.id)?' selected':'')),b=button('',()=>{},'group-open');let timer;
    const enter=()=>{clearTimeout(timer);currentFolder=folder.id;selected.clear();$('#search').value='';render()};
    b.onclick=()=>{clearTimeout(timer);timer=setTimeout(()=>toggleSelected(folder.id),240)};b.ondblclick=enter;b.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();enter()}};
    b.setAttribute('aria-label','文件夹 '+folder.name);b.title='单击选择，双击打开';b.setAttribute('aria-pressed',selected.has(folder.id));b.append(folderCover(members),groupMeta(folder.name,members.length+' 个素材'));const openButton=button('打开',enter,'ds-rename');openButton.setAttribute('aria-label','打开文件夹 '+folder.name);wrapper.append(b,selectionCheck(folder),openButton);grid.append(wrapper)}
  window.lucide?.createIcons();
}
function groupMeta(name,detail){const meta=el('div',undefined,'group-meta'),title=el('strong',name);title.title=name;meta.append(title,el('p',detail));return meta}
function folderCover(members){const art=el('div',undefined,'asset-art folder-cover'),images=members.filter(r=>r.preview||(r.blob?.type.startsWith('image/')&&!/svg/.test(r.blob.type))).slice(0,4);art.dataset.count=images.length;
  if(!images.length){const icon=el('i');icon.dataset.lucide='folder';art.append(icon)}
  images.forEach(r=>{const cell=el('div',undefined,'collage-cell'),img=new Image();img.alt='';img.loading='lazy';if(r.preview)img.src=r.preview;else{const url=URL.createObjectURL(r.blob);urls.push(url);img.src=url}img.onerror=()=>{img.remove();const icon=el('i');icon.dataset.lucide='image-off';cell.append(icon);window.lucide?.createIcons()};cell.append(img);art.append(cell)});
  const badge=el('span',undefined,'folder-badge'),icon=el('i');icon.dataset.lucide='folder';badge.append(icon);badge.setAttribute('aria-hidden','true');art.append(badge);return art;
}
$('#new-folder').onclick=()=>{open('新建文件夹');const label=el('label','文件夹名称','field'),input=el('input');input.placeholder='未命名文件夹';input.maxLength=80;label.append(input);const save=button('创建',async()=>{if(!input.value.trim()){input.focus();return}busy=true;save.disabled=true;try{await D.createFolder(input.value);busy=false;close();await refresh();notify('文件夹已保存到本机')}catch(e){busy=false;save.disabled=false;throw e}},'primary');input.onkeydown=e=>{if(e.key==='Enter'&&!save.disabled){e.preventDefault();save.click()}};body.append(label,save);input.focus()};
$('#move').onclick=()=>{const ids=[...selected];open('移动 '+ids.length+' 项素材');const label=el('label','目标文件夹','field'),select=el('select');select.add(new Option('Group（根目录）',''));folderRecords.forEach(f=>select.add(new Option(f.name,f.id)));select.value=currentFolder||'';label.append(select);const move=button('移动',async()=>{busy=true;move.disabled=true;try{if(select.value&&!(await D.folders()).some(f=>f.id===select.value))throw Error('目标文件夹已不存在，请重新选择');await D.updateFiles(all=>all.map(r=>ids.includes(r.id)?{...r,folderId:select.value||null}:r));busy=false;selected.clear();close();await refresh();notify('素材已移动')}finally{busy=false;move.disabled=false}},'primary');move.disabled=true;select.onchange=()=>move.disabled=select.value===(currentFolder||'');const actions=el('div',undefined,'modal-actions');actions.append(button('取消',close),move);body.append(label,actions)};
function renameDS(d){
  open('重命名 DS');const label=el('label','DS 名称','field'),input=el('input');input.value=d.name;input.maxLength=120;label.append(input);
  const error=el('p','','notes');error.setAttribute('role','alert');const actions=el('div',undefined,'modal-actions');
  const save=button('保存',async()=>{const name=input.value.trim();if(!name){error.textContent='请输入 DS 名称';input.focus();return}busy=true;save.disabled=true;try{await D.rename(d.id,name);busy=false;close();await refresh();notify('名称已保存到本机')}catch(e){busy=false;save.disabled=false;error.textContent=e.message||'保存失败，请重试'}},'primary');
  input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();if(!save.disabled)save.click()}};actions.append(button('取消',close),save);body.append(label,error,actions);input.focus();input.select();
}
function size(n){return n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB'}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;selected.clear();render()});$('#search').oninput=()=>{selected.clear();render()};
$('#clear-selection').onclick=()=>{selected.clear();render()};
$('#select-all').onclick=()=>{const q=$('#search').value.trim().toLowerCase(),list=tab==='ds'?documents:[...records.filter(r=>(r.folderId||null)===currentFolder),...(!currentFolder?folderRecords:[])];selected=new Set(list.filter(r=>r.name.toLowerCase().includes(q)).map(r=>r.id));render()};
function upload(){open('上传素材');const drop=button('',()=>$('#file-input').click(),'drop');drop.append(el('span','↑'),el('b','拖拽文件到此处，或点击上传'),el('small','图片、设计稿、文档及其他文件'));drop.ondragover=e=>{e.preventDefault();drop.classList.add('over')};drop.ondragleave=()=>drop.classList.remove('over');drop.ondrop=e=>{e.preventDefault();if(e.dataTransfer.files.length)choose([...e.dataTransfer.files])};const folderInput=el('input');folderInput.type='file';folderInput.multiple=true;folderInput.setAttribute('webkitdirectory','');folderInput.hidden=true;folderInput.onchange=()=>{if(folderInput.files.length)choose([...folderInput.files])};body.append(drop,button('选择文件夹',()=>folderInput.click()),folderInput)}
$('#upload').onclick=upload;$('#empty-upload').onclick=upload;$('#file-input').onchange=e=>{if(e.target.files.length)choose([...e.target.files]);e.target.value=''};
function choose(files){open('选择处理方式');const list=el('div',undefined,'file-list');files.forEach(f=>list.append(el('p',(f.webkitRelativePath||f.name)+' · '+size(f.size))));const choices=el('div',undefined,'choices');const direct=button('',()=>chooseDestination(files)),smart=button('',()=>analyzeFiles(files));direct.append(el('b','直接保存'),el('p','保留原文件，存入指定 Group 素材夹'));smart.append(el('b','智能解析 DS'),el('p','提取配色与原稿；AI 深度解析待配置'));choices.append(direct,smart);body.append(list,choices)}
const toRecords=(files,folderId=currentFolder)=>files.map(f=>({id:D.id(),name:f.name,blob:f,folderId,relativePath:f.webkitRelativePath||'',created:Date.now()}));
async function chooseDestination(files){open('保存到素材夹');const folders=await D.folders(),label=el('label','保存位置','field'),select=el('select');select.setAttribute('aria-label','保存位置');select.add(new Option('Group（根目录）',''));folders.forEach(f=>select.add(new Option(f.name,f.id)));select.value=currentFolder||'';label.append(select);const actions=el('div',undefined,'modal-actions');actions.append(button('返回',()=>choose(files)),button('确认保存',()=>saveFiles(files,select.value||null),'primary'));body.append(label);if(files.some(f=>f.webkitRelativePath))body.append(el('p','本版将文件夹内文件统一存入所选位置，保留原相对路径记录；不创建嵌套文件夹。','notes'));body.append(actions)}
async function saveFiles(files,folderId=currentFolder){busy=true;body.replaceChildren(el('p','正在保存原文件…'));try{if(folderId&&!(await D.folders()).some(f=>f.id===folderId))throw Error('目标文件夹已不存在，请重新选择');await D.updateFiles(old=>[...old,...toRecords(files,folderId)]);busy=false;close();tab='group';currentFolder=folderId;await refresh();notify('已保存到 Group')}catch(e){fail(Error('本机保存失败：'+e.message+'。原文件仍保留，可重试。'));body.append(button('重新选择位置',()=>chooseDestination(files)),button('重试',()=>saveFiles(files,folderId)))}}
async function pdfImage(file){if(location.protocol==='file:')throw Error('PDF 解析请在本地服务页面打开，图片解析不受影响。');const pdfjs=await import('./pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='./pdf.worker.mjs';const task=pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),isEvalSupported:false,useSystemFonts:true});let pdf;try{pdf=await task.promise;const page=await pdf.getPage(1),v=page.getViewport({scale:1}),viewport=page.getViewport({scale:Math.min(2,1800/Math.max(v.width,v.height))}),canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;const content=await page.getTextContent(),names=[...new Set(Object.values(content.styles).map(s=>s.fontFamily))];const blob=await new Promise(r=>canvas.toBlob(r));return {image:await D.analyzeImage(blob),notes:'PDF 共 '+pdf.numPages+' 页，本次解析第 1 页。文本字体映射：'+(names.join('、')||'未发现可提取文字')+'；嵌入字体未导入编辑器。'}}finally{if(pdf)await pdf.destroy();else await task.destroy()}}
async function analyzeFiles(files,existing=false){const token=open('正在解析素材');busy=true;body.append(el('p','正在读取真实像素和文件信息…'));try{const results=[];for(const f of files){const name=f.name.toLowerCase();if(name.endsWith('.pdf')){results.push({name:f.name,...await pdfImage(f)});continue}if(!f.type.startsWith('image/')&&!/\.(png|jpe?g|webp|gif|svg|avif|bmp)$/.test(name))throw Error(f.name+' 可保存在 Group；解析设计稿请上传图片、SVG 或 PDF，PSD / AI 请先导出。');let notes='配色来自图片像素；字体、组件语义与布局规则需要人工确认。';if(name.endsWith('.svg')){const xml=new DOMParser().parseFromString(await f.text(),'image/svg+xml');if(xml.querySelector('parsererror,script,foreignObject')||[...xml.querySelectorAll('*')].some(n=>[...n.attributes].some(a=>/^on/i.test(a.name)||(/href$/i.test(a.name)&&!a.value.startsWith('#')))))throw Error('SVG 包含外部引用或脚本，请先导出为 PNG。');notes='配色来自 SVG 渲染；字体声明：'+([...new Set([...xml.querySelectorAll('[font-family]')].map(n=>n.getAttribute('font-family')))].join('、')||'未声明')+'。字体文件未导入。'}results.push({name:f.name,image:await D.analyzeImage(f),notes})}if(token!==generation)return;busy=false;const palette=[...new Set(results.flatMap(r=>r.image.palette))].slice(0,5),d=D.make(files[0].name.replace(/\.[^.]+$/,'')+' · DS',palette,{type:'image',files:files.map(f=>f.name),date:new Date().toISOString(),notes:results.map(r=>r.name+'：'+r.notes).join('\n')});results.forEach((r,i)=>{D.referenceBoard(d,r.image,r.name);d.boards[d.boards.length-1].name=String(i+2).padStart(2,'0')+' / '+r.name});review(d,palette,existing?[]:files)}catch(e){if(token!==generation)return;fail(e);body.append(button('返回处理方式',()=>choose(files)));if(!existing)body.append(button('仅保存原文件',()=>saveFiles(files)))}}
function review(d,palette,files=[]){open(d.source.ai?'AI 解析完成':'基础提取完成');const label=el('label','DS 名称','field'),name=el('input');name.value=d.name;label.append(name);body.append(label);const preview=el('div',undefined,'analysis-preview'),asset=Object.values(d.assets)[0];if(asset){const img=new Image();img.src=asset.data;img.alt='原稿预览';preview.append(img)}const colors=el('div',undefined,'colors');palette.forEach((color,i)=>{const l=el('label',i===0?'主色':i===1?'辅色':'参考色'),input=el('input');input.type='color';input.value=color;input.oninput=()=>{palette[i]=input.value;if(i===0)d.tokens.primary=input.value;if(i===1)d.tokens.secondary=input.value;const rect=d.boards.find(b=>b.name.includes('色彩系统'))?.nodes.filter(n=>n.type==='rect'&&n.h>10)[i];if(rect)rect.fill=input.value;const label=d.boards.find(b=>b.name.includes('色彩系统'))?.nodes.find(n=>n.text===color.toUpperCase());if(label)label.text=input.value.toUpperCase()};l.append(input);colors.append(l)});preview.append(colors);body.append(preview,el('p',d.source.notes,'notes'));if(d.source.url){const a=el('a',d.source.url,'source-link');a.href=d.source.url;a.target='_blank';a.rel='noopener noreferrer';body.append(a)}const actions=el('div',undefined,'modal-actions');body.append(button(d.source.ai?'重新 AI 解析':'AI 深度解析',()=>aiReview(d,palette,files)));actions.append(button('取消',close),button('保存为新 DS',async()=>{if(!name.value.trim()){name.focus();return}d.name=name.value.trim();busy=true;actions.querySelectorAll('button').forEach(b=>b.disabled=true);try{if(files.length){await D.updateFiles(old=>[...old,...toRecords(files)]);files=[]}await D.upsert(d);busy=false;close();tab='ds';await refresh();notify('DS 已保存，可进入编辑并导出 PDF')}catch(e){busy=false;actions.querySelectorAll('button').forEach(b=>b.disabled=false);throw Error('保存失败，请检查本机存储空间后重试。')}},'primary'));body.append(actions)}
async function aiReview(d,palette,files){
  open('AI 深度解析');
  const status=el('p','正在检查 AI 配置…','notes');body.append(status);
  if(!localService){status.textContent='在线演示版暂未连接 AI 服务，不会调用模型或产生费用。';body.append(button('返回基础提取结果',()=>review(d,palette,files)));return}
  let configured=false;try{configured=(await (await fetch('/api/ai/status')).json()).configured}catch(e){}
  if(!configured||location.protocol==='file:'){status.textContent='AI 待接入。当前不会调用模型或产生费用。';body.append(el('p','接入后将分析视觉风格、色彩层级、字体特征、排版规律和物料复用规则。','notes'),button('返回基础提取结果',()=>review(d,palette,files)));return}
  status.textContent='将把当前原稿预览和样式证据发送至 OpenAI 分析，费用由你配置的 API 账户承担。';
  body.append(button('取消',()=>review(d,palette,files)),button('确认并解析',async()=>{
    busy=true;body.replaceChildren(el('p','AI 正在分析设计风格…'));
    try{const response=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json','X-DS-Request':'1'},signal:AbortSignal.timeout(130000),body:JSON.stringify({images:Object.values(d.assets).map(a=>a.data).slice(0,6),evidence:{source:d.source,tokens:d.tokens}})});const result=await response.json();if(!response.ok)throw Error(result.error||'AI 解析失败');
      const a=result.analysis;for(const key of ['primary','secondary','background','ink','muted','heading','body','radius'])d.tokens[key]=a[key];d.name=a.name;d.layout=a.layout;d.vi=false;d.source.ai={model:result.model,analysis:a,date:new Date().toISOString()};d.source.notes=a.summary+'\n排版规则：\n'+a.layoutRules.join('\n')+'\n复用规则：\n'+a.reuseRules.join('\n')+'\n待确认：\n'+a.uncertainties.join('\n');
      const board=D.board('AI / 风格与复用规则');board.nodes.push(D.node('text',{x:60,y:50,w:1080,h:70,text:a.name,size:36}),D.node('text',{x:60,y:150,w:1080,h:130,text:a.summary,size:22,font:'body'}));a.layoutRules.slice(0,5).forEach((rule,i)=>board.nodes.push(D.node('text',{x:60,y:325+i*86,w:500,h:76,text:rule,size:17,font:'body'})));a.reuseRules.slice(0,5).forEach((rule,i)=>board.nodes.push(D.node('text',{x:650,y:325+i*86,w:490,h:76,text:rule,size:17,font:'body'})));d.boards=d.boards.filter(b=>b.name!=='AI / 风格与复用规则');d.boards.push(board);busy=false;review(d,[a.primary,a.secondary,a.muted,a.background,a.ink],files);
    }catch(e){busy=false;fail(e);body.append(button('返回原结果',()=>review(d,palette,files)))}
  },'primary'));
}
async function resource(url){if(!localService)throw Error('在线演示版暂未连接网站解析服务，请改为上传网页截图。');let r;try{r=await fetch('/api/fetch?url='+encodeURIComponent(url),{signal:AbortSignal.timeout(22000)})}catch(e){throw Error('本地网站解析服务未连接或请求超时。请确认服务正在运行，或上传网页截图解析。')}const data=await r.json();if(!r.ok)throw Error(data.error||'网站读取失败');return data}
const decode=r=>new TextDecoder().decode(Uint8Array.from(atob(r.data),c=>c.charCodeAt(0)));
async function website(url){const token=open('正在读取网站');busy=true;body.append(el('p','读取公开页面、样式与视觉素材…'));try{const response=await resource(url);if(!response.type.includes('html'))throw Error('请输入网页地址，而不是文件下载地址。');const html=new DOMParser().parseFromString(decode(response),'text/html');const css=[...html.querySelectorAll('style')].map(n=>n.textContent),warnings=[],fonts=new Set(),counts=new Map();for(const link of [...html.querySelectorAll('link[rel="stylesheet"]')].slice(0,5)){try{css.push(decode(await resource(new URL(link.getAttribute('href'),response.url).href)))}catch(e){warnings.push('部分外部样式读取失败')}}
  const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');function color(v,weight){if(!CSS.supports('color',v)||/var\(|currentColor|transparent|inherit/i.test(v))return;ctx.fillStyle='#010203';ctx.fillStyle=v;const hex=ctx.fillStyle;if(/^#[\da-f]{6}$/i.test(hex))counts.set(hex,(counts.get(hex)||0)+weight)}
  function rules(list){for(const rule of list){if(rule.style){for(const property of rule.style){const value=rule.style.getPropertyValue(property);if(property==='font-family')fonts.add(value);if(/color|background|fill|^--/.test(property))color(value,rule.selectorText?.includes(':root')?30:1)}}if(rule.cssRules)rules(rule.cssRules)}}
  for(const text of css){const sheet=new CSSStyleSheet();sheet.replaceSync(text);rules(sheet.cssRules)}for(const n of html.querySelectorAll('[style]')){for(const prop of n.style)if(/color|background/.test(prop))color(n.style.getPropertyValue(prop),1)}
  const palette=[...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5).map(x=>x[0]);if(!palette.length)throw Error('未读取到可用的公开配色。该网站可能依赖登录或动态加载，请上传截图解析。');
  const name=(html.title||new URL(url).hostname).trim().slice(0,70),d=D.make(name+' · DS',palette,{type:'website',url:response.url,date:new Date().toISOString(),fonts:[...fonts].slice(0,20),notes:'配色来自公开 CSS 声明，非逐元素渲染统计。字体声明：'+([...fonts].slice(0,8).join('、')||'未发现')+'。字体文件未导入，编辑器使用系统字体。布局由工具整理，动态内容与组件语义需人工确认。'});
  const candidates=[html.querySelector('meta[property="og:image"]')?.content,...[...html.querySelectorAll('img[src]')].map(n=>n.getAttribute('src'))].filter(Boolean);
  for(const src of candidates.slice(0,4)){try{const r=await resource(new URL(src,response.url).href);if(!r.type.startsWith('image/')||r.type.includes('svg'))continue;const blob=new Blob([Uint8Array.from(atob(r.data),c=>c.charCodeAt(0))],{type:r.type}),image=await D.analyzeImage(blob);D.referenceBoard(d,image,'官网素材');break}catch(e){warnings.push('部分图片未能读取')}}
  if(!Object.keys(d.assets).length)warnings.push('未提取到静态图片，可在编辑器补充原稿');d.source.notes+='\n'+[...new Set(warnings)].join('；');if(token!==generation)return;busy=false;review(d,palette)
}catch(e){if(token!==generation)return;fail(e);body.append(button('重新输入网址',websiteDialog))}}
function websiteDialog(){open('解析网站');const label=el('label','网站地址','field'),input=el('input');input.type='url';input.placeholder='https://www.example.com';label.append(input);body.append(label,el('p','读取公开样式与图片，不访问登录内容。','notes'),button('开始解析',()=>{let u;try{u=new URL(input.value);if(u.protocol!=='https:')throw Error()}catch(e){throw Error('请输入完整的 HTTPS 网站地址')}return website(u.href)},'primary'));input.focus()}
$('#website').onclick=websiteDialog;
$('#ai-config').onclick=()=>{open('AI 解析 · 待接入');body.append(el('p','暂未配置模型 API，不会产生 AI 调用费用。'),el('p','接入后可从图片、设计稿与网站样式分析完整视觉风格，并保存为可编辑 DS。','notes'),button('知道了',close))};
$('#analyze-selected').onclick=()=>analyzeFiles(records.filter(r=>selected.has(r.id)).map(r=>new File([r.blob],r.name,{type:r.blob.type})),true);
$('#rename').onclick=()=>{if(tab==='ds'){const d=documents.find(d=>selected.has(d.id));if(d)renameDS(d);return}const r=[...records,...folderRecords].find(r=>selected.has(r.id));if(!r)return;const folder=folderRecords.some(f=>f.id===r.id);open('重命名');const input=el('input');input.value=r.name;input.maxLength=folder?80:240;const field=el('label',folder?'文件夹名称':'文件名','field');field.append(input);body.append(field,button('保存',async()=>{const name=input.value.trim();if(!name)throw Error('名称不能为空');if(folder)await D.renameFolder(r.id,name);else await D.updateFiles(all=>all.map(x=>x.id===r.id?{...x,name}:x));close();await refresh();notify('名称已保存')},'primary'));input.focus()};
$('#delete').onclick=()=>{const ids=[...selected],isDS=tab==='ds',folders=folderRecords.filter(f=>ids.includes(f.id)),contained=records.filter(r=>folders.some(f=>f.id===r.folderId)).length;open(isDS?'删除 Design System':'删除素材');const message=isDS?'确认删除选中的 '+ids.length+' 套 DS？其画板和内嵌素材将一并删除，Group 原文件不受影响。':'确认删除选中的 '+ids.length+' 项？'+(folders.length?'包含 '+folders.length+' 个文件夹及其中 '+contained+' 个素材。':'')+'已生成的 DS 不受影响。';const actions=el('div',undefined,'modal-actions'),remove=button('确认删除',async()=>{busy=true;remove.disabled=true;try{if(isDS)await D.removeDS(ids);else await D.removeAssets(ids);busy=false;selected.clear();close();await refresh();notify('已删除')}finally{busy=false;remove.disabled=false}},'danger');actions.append(button('取消',close),remove);body.append(el('p',message),actions)};
$('#download').onclick=()=>{for(const r of records.filter(r=>selected.has(r.id))){const a=el('a'),url=URL.createObjectURL(r.blob);a.href=url;a.download=r.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}};
async function beginDesign(chosen){const start=$('#start');start.disabled=true;try{if(!chosen.length)throw Error('请先选择素材');const assets=await Promise.all(chosen.map(async r=>{if(r.preview||!r.blob.type.startsWith('image/'))return r;try{return {...r,preview:(await D.analyzeImage(r.blob)).data}}catch(e){return r}}));const p=await D.createCanvas({source:'assets',assets});const url=new URL('workbench-v042-additions.html',location.href);url.searchParams.set('canvasProject',p.id);if(new URLSearchParams(location.search).get('client')==='desktop')url.searchParams.set('client','desktop');url.hash='canvas';window.top.location.href=url.href}catch(e){fail(e);start.disabled=false}}
$('#start').onclick=()=>{const chosen=chosenFiles();if(!folderRecords.some(f=>selected.has(f.id)))return beginDesign(chosen);open('确认参考素材');const use=new Set(chosen.filter(r=>selected.has(r.id)).map(r=>r.id)),start=button('开始设计',()=>{start.disabled=true;return beginDesign(chosen.filter(r=>use.has(r.id)))},'primary');start.disabled=!use.size;body.append(el('p','选择本次设计要引用的文件夹内容：','notes'));for(const r of chosen){const label=el('label',undefined,'field'),check=el('input');check.type='checkbox';check.checked=use.has(r.id);check.onchange=()=>{check.checked?use.add(r.id):use.delete(r.id);start.disabled=!use.size};label.append(check,document.createTextNode(r.name));body.append(label)}body.append(start)};
window.addEventListener('focus',()=>{if(!modal.open)refresh().catch(fail)});
D.seed().then(refresh).catch(fail);
})();
