(() => {
'use strict';
const D=window.DSData,$=s=>document.querySelector(s),clone=v=>structuredClone(v);
let project=null,homeDS=null,loading=null,sending=false;
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
const btn=(label,fn,cls)=>{const b=el('button',label,cls);b.type='button';b.onclick=fn;return b};
const style=el('link');style.rel='stylesheet';style.href='canvas-ds.css';document.head.append(style);
const notify=message=>{const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>t.classList.remove('show'),4000)};
const dialog=el('dialog',undefined,'canvas-ds-dialog');dialog.setAttribute('aria-label','选择 Design System');document.body.append(dialog);
const chips=document.querySelectorAll('.canvas-chip'),chip=btn('选择 Design System',()=>choose(false),'canvas-chip bound-ds-chip');chips[2].replaceWith(chip);
const badge=btn('',()=>choose(false),'canvas-ds-badge');$('.canvas-surface').append(badge);
const homeTool=document.querySelectorAll('#create .tool')[2],homeChoice=homeTool.cloneNode(true);homeTool.replaceWith(homeChoice);homeChoice.onclick=()=>choose(true);homeChoice.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(true)}};
const timeline=el('div',undefined,'canvas-ds-history');timeline.setAttribute('aria-label','设计需求记录');$('.canvas-composer').before(timeline);
const oldSend=$('.canvas-send'),send=oldSend.cloneNode(true);oldSend.replaceWith(send);send.setAttribute('aria-label','提交画布设计需求');
function currentDS(){return project?.bindings[project.activeBinding]||null}
function queryProject(){return new URLSearchParams(location.search).get('canvasProject')}
function setProjectURL(id){const url=new URL(location.href);if(id)url.searchParams.set('canvasProject',id);else url.searchParams.delete('canvasProject');history.replaceState(null,'',url.pathname+url.search+url.hash)}
async function ensureProject(){if(project)return project;if(loading)return loading;loading=(async()=>{const id=queryProject(),list=await D.canvasProjects();project=list.find(p=>p.id===id)||null;if(id&&!project)throw Error('这个画布已不存在，请从 Project 重新打开');if(!project){project=await D.createCanvas(null);setProjectURL(project.id)}render();return project})().finally(()=>loading=null);return loading}
function render(){if(!project)return;const ds=currentDS();chip.textContent=ds?ds.name:'选择 Design System';chip.title=ds?'当前画布 DS：'+ds.name+' · 点击切换':'选择此画布的 Design System';chip.setAttribute('aria-label',chip.title);chip.classList.toggle('selected',!!ds);badge.replaceChildren();const mark=el('span',undefined,'binding-dot');mark.style.background=ds?.tokens.secondary||'#b9c0c5';badge.append(mark,el('span',ds?'DS · '+ds.name:'选择 Design System'));badge.title=chip.title;
 const title=$('.canvas-top-tools');title.replaceChildren(el('span','Canvas - '+project.name));chips[1].textContent=project.name;$('.chat-head').textContent='New Chat';timeline.replaceChildren();$('.chat-welcome').hidden=project.requests.length>0;$('.canvas-category-row').hidden=project.requests.length>0;
 for(const request of project.requests){const row=el('article',undefined,'canvas-ds-request'),bound=project.bindings[request.designSystemKey];row.append(el('p',request.prompt),el('small',bound?'DS · '+bound.name:'未选择 DS'),el('span','待生成 · AI 尚未接入','request-pending'));timeline.append(row)}
 $('#canvas').dataset.designSystemId=ds?.id||'';$('#canvas').dataset.projectId=project.id;
}
async function choose(home){try{if(!home)await ensureProject();const library=await D.getLibrary(),systems=library?.documents.filter(d=>d.kind!=='material')||[];dialog.replaceChildren();const head=el('header');head.append(el('h2','选择 Design System'),btn('×',()=>dialog.close(),'ds-picker-close'));head.lastChild.setAttribute('aria-label','关闭');const list=el('div',undefined,'ds-picker-list');const active=home?homeDS?.id:currentDS()?.id;for(const ds of systems){const option=btn('',async()=>{option.disabled=true;try{if(home){homeDS=clone(ds);homeChoice.textContent=ds.name;homeChoice.title=ds.name;homeChoice.setAttribute('aria-label','Design System：'+ds.name)}else{project=await D.bindCanvas(project.id,ds.id);render();notify('后续设计将使用「'+ds.name+'」')}dialog.close()}catch(e){option.disabled=false;notify(e.message)}},'ds-picker-option');option.setAttribute('aria-pressed',String(active===ds.id));const colors=el('span',undefined,'ds-picker-colors');[ds.tokens.primary,ds.tokens.secondary,ds.tokens.background].forEach(c=>{const dot=el('i');dot.style.background=c;colors.append(dot)});option.append(colors,el('strong',ds.name),el('small',active===ds.id?'已选择':ds.boards.length+' 个画板'));list.append(option)}if(!systems.length){list.append(el('p','暂无 Design System'),btn('前往 Assets',()=>{dialog.close();location.hash='#assets'}))}dialog.append(head,list);dialog.showModal()}catch(e){notify(e.message)}}
async function submit(){if(sending)return;const input=$('.canvas-live-input'),prompt=input.textContent.trim();if(!prompt)return notify('请先描述设计需求');sending=true;send.disabled=true;try{await ensureProject();project=await D.submitCanvas(project.id,prompt);input.textContent='';send.classList.remove('ready');render();await renderProjects();notify('需求与画布 DS 已保存，AI 生成待接入')}catch(e){notify('保存失败：'+e.message)}finally{sending=false;send.disabled=false}}
send.onclick=submit;
$('.canvas-live-input').addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();submit()}});
$('.send').addEventListener('click',async e=>{const text=$('#create .prompt').textContent.trim();if(!text&&!homeDS)return;e.stopImmediatePropagation();if(sending)return;sending=true;try{project=await D.createCanvas(homeDS?.id);if(text)project=await D.submitCanvas(project.id,text);setProjectURL(project.id);render();location.hash='#canvas';await renderProjects()}catch(error){notify(error.message)}finally{sending=false}},{capture:true});
async function renderProjects(){const grid=$('#projects .card-grid'),list=await D.canvasProjects();grid.querySelectorAll('[data-canvas-project]').forEach(c=>c.remove());let after=grid.querySelector('.new');for(const item of [...list].sort((a,b)=>b.modified-a.modified)){const card=btn('',async()=>{project=null;setProjectURL(item.id);location.hash='#canvas';try{await ensureProject()}catch(e){notify(e.message)}},'card canvas-project-card');card.dataset.canvasProject=item.id;const ds=item.bindings[item.activeBinding],art=el('div',undefined,'project-preview'),swatches=el('div',undefined,'bound-project-swatches');if(ds)[ds.tokens.primary,ds.tokens.secondary,ds.tokens.background].forEach(c=>{const x=el('span');x.style.background=c;swatches.append(x)});art.append(swatches);const copy=el('div',undefined,'copy');copy.append(el('h3',item.name),el('p',ds?'DS · '+ds.name:'未选择 DS'),el('p',item.requests.length+' 个设计需求'));card.append(art,copy);if(after)after.after(card);else grid.prepend(card);after=card}}
document.addEventListener('click',e=>{if(e.target.closest('#projects .card:not([data-canvas-project])')){project=null;setProjectURL(null)}},{capture:true});
async function route(){if(location.hash==='#canvas'){try{await ensureProject();render()}catch(e){notify(e.message)}}if(location.hash==='#projects')renderProjects().catch(e=>notify(e.message))}
addEventListener('hashchange',route);route();
})();
