(() => {
const $=s=>document.querySelector(s),icon=name=>{const i=document.createElement('i');i.dataset.lucide=name;return i};
const contact=$('.top-contact'),wechat=new Image();wechat.src='wechat.svg';wechat.alt='';wechat.className='wechat-icon';contact.querySelector('svg')?.replaceWith(wechat);contact.querySelector(':scope > span')?.remove();contact.setAttribute('role','button');contact.setAttribute('aria-label','微信联系我们');contact.title='微信联系我们';
const brandText=document.createElement('span');brandText.textContent='workbench';$('.brand-mark').replaceChildren(icon('asterisk'),brandText);
const footer=document.createElement('div');footer.className='sidebar-footer';footer.textContent='Personal workspace';$('.sidebar').append(footer);
const crumb=document.createElement('div');crumb.className='page-crumb';const parent=document.createElement('span');parent.textContent='Workspace /';const name=document.createElement('strong');crumb.append(parent,name);$('.topbar').prepend(crumb);
const pages={create:'Create',assets:'Assets',gallery:'Gallery',deliverables:'Deliverables',projects:'Projects',canvas:'Canvas'};const sync=()=>{name.textContent=pages[location.hash.slice(1)]||'Create';document.querySelectorAll('.mobile-nav a').forEach(a=>a.classList.toggle('active',a.hash===(location.hash||'#create')))};addEventListener('hashchange',sync);sync();
['square-pen','layers-2','lightbulb','package-check','folder'].forEach((name,i)=>{const a=document.querySelectorAll('.nav-link')[i],label=a.textContent.trim();a.replaceChildren(icon(name));const text=document.createElement('span');text.className='nav-label';text.textContent=label;a.append(text);a.setAttribute('aria-label',label);a.title=label;});
const collapse=document.createElement('button');collapse.className='sidebar-toggle';collapse.type='button';$('.collapse').replaceWith(collapse);
function setSidebar(collapsed){document.body.classList.toggle('sidebar-collapsed',collapsed);collapse.setAttribute('aria-expanded',String(!collapsed));collapse.setAttribute('aria-label',collapsed?'展开导航栏':'收起导航栏');collapse.title=collapsed?'展开导航栏':'收起导航栏';collapse.replaceChildren(icon(collapsed?'panel-left-open':'panel-left-close'));window.lucide?.createIcons();try{localStorage.setItem('workbench-sidebar-collapsed',String(collapsed))}catch(e){}}
collapse.onclick=()=>setSidebar(!document.body.classList.contains('sidebar-collapsed'));let collapsed=false;try{collapsed=localStorage.getItem('workbench-sidebar-collapsed')==='true'}catch(e){}setSidebar(collapsed);
const eyebrow=document.createElement('div');eyebrow.className='create-eyebrow';eyebrow.textContent='YOUR NEXT IDEA STARTS HERE';$('.hero').prepend(eyebrow);
['plus','layers-2','swatch-book','image','folder'].forEach((name,i)=>{const tool=document.querySelectorAll('#create .tool')[i];if(!tool)return;if(i===0)tool.replaceChildren(icon(name));else tool.prepend(icon(name));tool.setAttribute('role','button');tool.tabIndex=0;tool.setAttribute('aria-label',i===0?'上传素材':tool.textContent);tool.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();tool.click()}})});
$('.send').setAttribute('aria-label','开始设计');$('.send').title='开始设计';
const showcase=document.createElement('section');showcase.className='showcase';showcase.innerHTML='<header class="showcase-heading"><h2>Showcase</h2><a href="#gallery">View gallery <i data-lucide="arrow-up-right"></i></a></header><div class="showcase-grid"></div>';
const projects=[['FORM / Daily essentials','Packaging · Visual identity','参考 FORM 的简洁银色与绿色风格，设计一套产品包装'],['OFF GRID / A new perspective','Campaign · Art direction','参考 OFF GRID 的黑色与荧光绿，设计一套活动海报'],['DAY / A little tea ritual','Branding · Packaging','参考 DAY 的红白品牌风格，设计一套茶饮品牌视觉']];
projects.forEach(([title,type,prompt])=>{const b=document.createElement('button');b.className='showcase-item';b.innerHTML='<span class="showcase-art"></span><span class="showcase-meta"><span><strong></strong><small></small></span><i data-lucide="arrow-up-right"></i></span>';b.querySelector('strong').textContent=title;b.querySelector('small').textContent=type;b.onclick=()=>{const input=$('#create .prompt');input.textContent=prompt;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus()};showcase.querySelector('.showcase-grid').append(b)});$('#create .inner').append(showcase);
document.querySelectorAll('#gallery .card').forEach((card,i)=>{card.querySelector('h3').textContent=projects[i][0]});
window.lucide?.createIcons();
})();
